
sudo: required
language: java

jdk:
  - oraclejdk8

script:
  - mvn clean cobertura:cobertura -Dtest=CloudFoundryClientTest#getApplicationInstances -DfailIfNoTests=false

before_deploy:
- tar -zcvf coverage-result.tar.gz /home/travis/build/leusonmario/cf-java-client/target/site/cobertura

deploy:
  provider: releases
  api_key:
    secure: "e5XZUk4OOeyrCX+OEZBdQsYdW12bofRjNfIqpXF3FvvZ0oKKM7k4pLiixokLkZxEcnp+Y7Lb40ryZgRDN/3FOQFa8eiWm4E9UBrO1AXeytn4aQviav15CNfRCJ9yNtcUIV0+u7P0lkr2afMEz4rBC2ZiTFisFqNBOFQUD71D2bqgXcyuvjt82JFFSjTG8JASSA6K/dk2zUzpZZQ9Eox1AoFY2wRjxgXb2POf71c93t/sfYRBfH2oa3YE0zd2qrGRJ5L252Ya1whrmESSCvwbiHYuF7qYCXi4/VTzXXKDF/zlnWmSGhM3yOzaDC9YHDP5dIdYuOp3pWb+FvX81UfUeP/M2EvyP+UwPeCFvRYw/1wtSdqW+OyUF7YiMM2MkGfQOH190ZNU9Twy599TABCPLqjKvwkYwmCZfu2JFRlN7ifJFJvoKrlXORM8KDqLcNkWIyX9nvPt6tCFy+EhKrzvM9/qluLVafGlmX9Mh0IYmO6EQiPkQIXec4SxxhBUYXfNFeVN1Zfx4LzwsTh0XIHRQKc06hf89OGNzGHKyCxk86hHfXooh1pUDbtyuwTm9eiMpKxQOGBjsWlWDap+mSorYEbakfPAPHbthGuQvGAMFqLwvavYblm6aL23o6Ja+y9SvRpfHruQytT4AtlCsfcdNTb0uU5ue99Nj+wtev5cwsI="


  file: coverage-result.tar.gz
  file_glob: true
  overwrite: true
  skip_cleanup: true
  on:
    tags: true
